import React, { useContext } from 'react'
import styles from './styles.module.css'
import classNames from 'classnames'
import { ThemeContext } from '@Contexts/index'
import DashboardLayout from '@Components/layouts/Dashboard/DashboardLayout'
import TaskLayout from '@Components/layouts/Task'
import { NextPageWithLayout } from '@Pages/_app'
import { ReactElement } from 'react'
import Table from '@Components/customs/Table'

const headers = {
  es: {
    personalID: 'Id Personal',
    name: 'Nombre',
    surname: 'Apellido',
    identityCard: 'N° de Identidad',
    typeCard: 'Documento',
    phoneNumber: 'Telefono',
    workArea: 'Area',
    job: 'Puesto',
    salary: 'Salario',
    refiment: 'Regimen',
    workingDay: 'jornada',
    timeControl: 'Control Horario',
    contract: 'Contrato',
    startContract: 'Inicio',
    endContract: 'Finalizacion',
    payAccount: 'Cuenta de Pago',
    bankAccount: 'Cuenta Bancaria',
    status: 'Estado',
    addedDate: 'Registro',
    alterDate: 'Modificacion',
    lowDate: 'Baja',
    userAdd: 'Registrador',
    userAlter: 'Modificador',
    userLow: 'Finalizador',
  },
}

const getHead = (data: any) => {
  const head = []

  for (const key in data) {
    head.push(data[key])
  }
  return head
}
const head = getHead(headers.es)

const fecha = new Date()
const Personal: NextPageWithLayout = () => {
  const { theme } = useContext(ThemeContext)
  return (
    <div className={classNames(styles.personal, styles[theme])}>
      <Table headers={head} records={rows} />
    </div>
  )
}

Personal.getLayout = function getLayout(page: ReactElement) {
  return (
    <DashboardLayout>
      <TaskLayout>{page}</TaskLayout>
    </DashboardLayout>
  )
}

export default Personal

const rows = [
  {
    id: '1',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '2',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '3',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '4',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '5',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '6',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '7',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '8',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '9',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '10',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '11',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '12',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '13',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '14',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '15',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '16',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '17',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '18',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '19',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
  {
    id: '20',
    name: 'Luis',
    surname: 'Pérez',
    identityCard: '081-250860-0008M',
    typeCard: 'Cedula',
    phoneNumber: '+505 8455-5589',
    workArea: 'Administración',
    job: 'Administrador',
    salary: '28000',
    refiment: 'General',
    workingDay: 'General',
    timeControl: 'No',
    contract: 'Permanente',
    startContract: fecha.toLocaleDateString(),
    endContract: fecha.toLocaleDateString(),
    payAccount: 'ACH',
    bankAccount: '11318848',
    status: 'Active',
    addedDate: fecha.toLocaleDateString(),
    alterDate: fecha.toLocaleDateString(),
    lowDate: fecha.toLocaleDateString(),
    userAdd: 'Luichix',
    userAlter: 'Luichix',
    userLow: 'Luichix',
  },
]
